### ISSUE TITLE
Cool acronym 

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#1]
First things first, we need a showstopper of an acronym for this project.  Add your suggestions as comments in this issue. 

(I can change this repo's name to the acronym once identified)

**Comment by laurahspencer** [comment]
**DuMOAR**
**Du**ngeness **M**ulti-**O**mics **A**cidification **R**esearch 

**DuMOE**
**Du**ngeness **M**ulti-**O**mics **E**xperiment

**DuMORA**
**Du**ngeness **M**ulti-Omics **R**esponse to **A**cidification 

**DIOR**
**D**ungeness **I**ntegrated **O**mics **R**esearch

**Comment by sr320** [comment]
nailed it...

DuMOAR!

**Comment by mgavery** [comment]
dang, totally nailed it
