### ISSUE TITLE
Submit raw MBD-BS and RNA-Seq data to NCBI

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#13]

**Comment by kristamnichols** [comment]
Link to sample IDs sheet for upload to NCBI: https://docs.google.com/spreadsheets/d/1ym0XnYVts98tIUCn0kIaU6VuvqxzV7LoSx9RHwLdiIs/edit?usp=sharing

**Comment by kristamnichols** [comment]
Link to SRA metadata files to upload to NCBI: https://drive.google.com/drive/folders/1KOhNCRKR_KqD3ay2Qbya8TOfzPGeK0LX?usp=share_link

**Comment by kristamnichols** [comment]
Need to rename the two lanes for MBD-seq so that filenames are unique to the lane that they are sequenced on at UO, especially since they have different read lengths (2x100 and 2x150). No need to upload the MiSeq data

**Comment by kristamnichols** [comment]
@ggoetznoaa let's rename the files in the folders /share/nwfsc/knichols/Dungeness/MBDseq_UOdata/4416 and /share/nwfsc/knichols/Dungeness/MBDseq_UOdata/4417 with their lane number pre-pended. For example, 4416_CH01_06_S1_L001_R1_001.fastq.gz, and then we can list 4 files per biosample in the NCBI upload (2 R1 and 2 R2). The RNAseq data were only collected in single lanes, and those data for upload are in /share/nwfsc/knichols/Dungeness/RNAseq_gill. MBDseq and RNAseq NCBI submission number SUB12303012

**Comment by kristamnichols** [comment]
Data submitted to NCBI and is procession. Project accession number is PRJNA906168
