### ISSUE TITLE
Incorporate MiSeq data from MBDBS libraries in meth. analysis?

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#16]
I could concatenate the MiSeq data to the MBDBS-Seq data before aligning, etc., to incorporate more reads/data. Thoughts?

**Comment by kubu4** [comment]
I think you might as well use the data. However, I'm still not convinced you should concatenate FastQs of mixed read lengths, different sequencers, etc.

What would be the rationale for concatenation?

**Comment by mgavery** [comment]
I don't know that it's worth it given the different read length/sequencer type.  It's roughly 500k reads per sample - not much considering ~17 millions reads per sample from HiSeq
