### ISSUE TITLE
Run Bismark on trimmed data prior to concatenation

### ISSUE THREAD

**Issue by sr320** [laurahspencer/DuMOAR#18]
and produced Bismark reports.

This will confirm abnormalities in results are sample specific and not associated with run.

**Comment by laurahspencer** [comment]
I'll run Bismark twice, one for each of the sequence runs.

**Comment by laurahspencer** [comment]
Bismark results for for 100 bp reads (aka 4416/): 
- [bismark report](https://github.com/laurahspencer/DuMOAR/blob/main/results/bismark/bismark_summary_report_4416.html)  
- [multiqc report](https://github.com/laurahspencer/DuMOAR/blob/main/results/bismark/multiqc_report_4416.html)

Bismark results for for 150 bp reads (aka 4417/): 
- [bismark report](https://github.com/laurahspencer/DuMOAR/blob/main/results/bismark/bismark_summary_report_4417.html)  
- [multiqc report](https://github.com/laurahspencer/DuMOAR/blob/main/results/bismark/multiqc_report_4417.html)

Very similar results from what I can tell
