### ISSUE TITLE
Submit Dungeness crab genome to NCBI

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#2]

**Comment by kristamnichols** [comment]
Submitted! Raw data is live, and the genome assembly is being reviewed by NCBI. Bioproject is PRJNA902360

**Comment by kristamnichols** [comment]
Dungeness genome now live on Genbank: SUB12287005, "Dungeness crab genome, Puget Sound, Washington, USA", accession number JAPQNM000000000 has been successfully released into GenBank
