### ISSUE TITLE
Pull Fastas based on two annotations and assess

### ISSUE THREAD

**Issue by sr320** [laurahspencer/DuMOAR#25]
Assess quality of annotation by determining completion of gene set.

**Comment by sr320** [comment]
@laurahspencer can you provide the two annotation files?

**Comment by laurahspencer** [comment]
GAWN (Genome Annotation Without Nightmares): 
- Following the [GAWN instructions](https://github.com/enormandeau/gawn) I ran the script [GAWN-annotation.sh](https://github.com/laurahspencer/DuMOAR/blob/main/scripts/GAWN-annotation.sh) using the scaffold-only genome, the transcriptome that Giles generated for me, the Swissprot database, and the config file [gawn_config.sh](https://github.com/laurahspencer/DuMOAR/blob/main/scripts/gawn_config.sh). All resulting files are on Google Drive [here](https://drive.google.com/drive/folders/1Z8I1rysEZfrtuZ83YKG26j0PHCffk1J3?usp=share_link), but the files <100MB are also in this repo [here](https://github.com/laurahspencer/DuMOAR/tree/main/results/GAWN/scaffold-only-assembly). Feel free to drop any files resulting from your work in either location. 

GenSaS: 
- All resulting files are on Google Drive [here](https://drive.google.com/drive/folders/1Z3jx1dcITEDegXwj4sOw2pUo4arKipZz?usp=share_link), and files <100 MB are also in this repo [here](https://github.com/laurahspencer/DuMOAR/tree/main/results/GenSAS) (which includes all except for the repeat elements). 
- If anyone has a GenSaS account I can share the project with you, I just need to know your username.

**Comment by kubu4** [comment]
I'll take a GenSas share!

User: `kubu4`

Thanks!

**Comment by laurahspencer** [comment]
@kubu4 just added you!

**Comment by sr320** [comment]
I say we go with GenSas annotation - needs to be trimmed up a bit to remove unscaffolded - did that (and more) here 

https://rpubs.com/sr320/1042307
