### ISSUE TITLE
Get RNA quality information from sequencing facility from library prep

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#34]
@mgavery @kristamnichols can either of you track down the RNA quality determined by the sequencing facility during extraction / library prep?

**Comment by kristamnichols** [comment]
QC reports for RNA
[sample qc -30-544518807-1 to 24_3f9d4531-fc48-414b-b001-27939ce803c2.pdf](https://github.com/laurahspencer/DuMOAR/files/12165955/sample.qc.-30-544518807-1.to.24_3f9d4531-fc48-414b-b001-27939ce803c2.pdf)
[Sample QC report of_30-544518807_210715022328.pdf](https://github.com/laurahspencer/DuMOAR/files/12165957/Sample.QC.report.of_30-544518807_210715022328.pdf)

**Comment by mgavery** [comment]
Thanks!  Those RIN values are pretty low, but I don't have a lot of experience with low RINs to know impact on library quality though.  @kristamnichols , do you know how they link the sample description ID in the report with our sample IDs? I'm wondering if any correlation between mapping rate and RIN

**Comment by kristamnichols** [comment]
@mgavery sample description is the 'genewiz id' in the other PDF, which links it to our sample IDs

**Comment by mgavery** [comment]
Thanks, I must have been clicking the same link over an over.  Ha! I didn't see the second report
