### ISSUE TITLE
Remove bacteria sequences from RNA-seq data

### ISSUE THREAD

**Issue by sr320** [laurahspencer/DuMOAR#35]
per https://github.com/laurahspencer/DuMOAR/issues/26#issuecomment-1613501939

mapping rates likely impacted by most sequences not crab...

Open to approach -

**Comment by sr320** [comment]
some summary stats

https://rpubs.com/sr320/1065657

**Comment by laurahspencer** [comment]
Decision 7/25 - keep RNASeq data that mapped to Arthropoda and Not Assigned for gene expression analysis. Remove rest.
