### ISSUE TITLE
RNASeq STAR alignment rates

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#37]
@ggoetznoaa can you add STAR output summary files to the /results/STAR/ directory? Looking for alignment rates by sample.

**Comment by ggoetznoaa** [comment]
@laurahspencer I've uploaded the STAR log files for each sample to the /results/STAR folder. This contains the output summary information for each sample.

**Comment by laurahspencer** [comment]
| Sample  | % uniquely aligned |
|---------|--------------------|
| CH07-04 | 40.80%             |
| CH09-28 | 37.01%             |
| CH05-07 | 35.98%             |
| CH01-14 | 32.41%             |
| CH07-06 | 32.21%             |
| CH07-11 | 30.48%             |
| CH05-14 | 29.59%             |
| CH05-29 | 28.19%             |
| CH01-22 | 28.14%             |
| CH03-33 | 27.52%             |
| CH07-24 | 26.34%             |
| CH01-06 | 25.38%             |
| CH05-09 | 24.63%             |
| CH10-11 | 24.58%             |
| CH03-04 | 24.58%             |
| CH10-08 | 24.44%             |
| CH01-38 | 24.06%             |
| CH07-08 | 23.94%             |
| CH05-01 | 23.17%             |
| CH05-06 | 21.78%             |
| CH09-02 | 18.72%             |
| CH09-13 | 17.62%             |
| CH03-15 | 17.55%             |
| CH05-21 | 14.11%             |

**Comment by laurahspencer** [comment]
RNASeq alignment rates don't match up with the % reads mapping to arthropoda (i.e. MEGAN results, see #26)

**Comment by kristamnichols** [comment]
@laurahspencer a scatterplot of %alignment vs. % reads arthropoda might be a good visualization if someone hasn't already done this?

**Comment by laurahspencer** [comment]
![image](https://github.com/laurahspencer/DuMOAR/assets/17264765/4c2c99c4-0677-4658-b1a6-f8daf315c294)
