### ISSUE TITLE
Align RNASeq to another crab genome

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#38]
Chinese mitten crab is a good option: https://www.nature.com/articles/s41467-021-22604-3

**Comment by ggoetznoaa** [comment]
Ok, so I mapped the MEGAN6 reads to the following mitten crab genome from NCBI

https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_024679095.1/

I used both STAR v2.7.10a and bowtie2 v2.5.0 to map the reads to the reference. In both cases I was getting mapping rates of 1-2% except for one sample, CH05-29, which had about 20% mapping rate although most of it was reads that were mapping multiple times.
