### ISSUE TITLE
Re-run STAR aligner using Dungeness crab and MEGAN-scrubbed RNASeq data

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#39]
@ggoetznoaa get scrubbed RNASeq data from @kubu4

**Comment by kubu4** [comment]
Alrighty, read extractions have been performed.

FastQs are here (`*.fq.gz`):

- https://gannet.fish.washington.edu/Atumefaciens/20230730.mmag-megan_reads/

MD5 checksums file:

- https://gannet.fish.washington.edu/Atumefaciens/20230730.mmag-megan_reads/checksums.md5

Notebook:

- https://robertslab.github.io/sams-notebook/2023/07/30/Read-Extractions-M.magister-MEGAN-FastA-to-FastQ-Arthropoda-and-Unassigned-Reads.html

@ggoetznoaa - Here's a direct link to Jupyter Notebook (NB Viewer) on how to use MEGAN FastAs to get corresponding reads from original FastQs. Let me know if you have any questions/concerns!

- https://nbviewer.org/github/RobertsLab/code/blob/master/notebooks/sam/20230730-mmag-megan-fasta_to_fastq.ipynb

**Comment by laurahspencer** [comment]
NEW APPROACH given that the de-novo transcriptome built from MEGAN-scrubbed reads might be pretty good, as per BUSCO results (~92% complete): 

@ggoetznoaa use Salmon to map ALL RNASeq reads to the trinity de-novo transcriptome built from MEGAN-scrubbed reads.

**Comment by ggoetznoaa** [comment]
Ran this using the script run.star_align_megan6_gensas.v1.sh, alignment stats found in spreadsheet
