### ISSUE TITLE
New RNASeq approach: de-novo transcriptome from MEGAN-scrubbed reads, Salmon for counts 

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#40]
@ggoetznoaa build a new transcriptome using the reads filtered to use only Arthropoda and Not Assigned reads (as per Megan), then generate counts using Salmon. Provide Laura with gene count matrix. 

Laura to perform differential expression analysis.

**Comment by ggoetznoaa** [comment]
Here is the genome I'm going to try, it doesn't look like its posted on NCBI.

http://www.genedatabase.cn/esi_genome.html

**Comment by ggoetznoaa** [comment]
Ok, I built a new transcriptome using Trinity v2.14.0 and all the MEGAN6 filtered reads. It generated 191492 contigs and 142402 'genes'. I then mapped the MEGAN6 reads using salmon v1.9.0 to the new transcriptome. I was getting roughly the following mapping rate percent stats.

```
 Min.   :92.72  
 1st Qu.:95.40  
 Median :95.89  
 Mean   :95.53  
 3rd Qu.:96.02  
 Max.   :96.66 
```

**Comment by laurahspencer** [comment]
@ggoetznoaa posted results to https://github.com/laurahspencer/DuMOAR/tree/main/results/salmon
