### ISSUE TITLE
Re-run Salmon alignment with --gcBias flag

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/DuMOAR#45]
In reviewing vignettes for software that I'm using to analyze the RNASeq data I came across the suggestion to include the [`--gcBias` flag](https://salmon.readthedocs.io/en/latest/salmon.html#gcbias) when running Salmon. See this excerpt from [the `tximport` vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#transcript-abundance-files-and-tximport-tximeta) that I'm using to summarize salmon alignments to estimated gene counts: 

"A tutorial on how to use the Salmon software for quantifying transcript abundance can be found here. We recommend using the --gcBias flag which estimates a correction factor for systematic biases commonly present in RNA-seq data (Love, Hogenesch, and Irizarry 2016; Patro et al. 2017), unless you are certain that your data do not contain such bias."

@ggoetznoaa it doesn't look like that was used when you ran Salmon, and in looking at the MultiQC report there could be some GC bias happening, so could you re-run Salmon with that flag?  See [this GitHub](https://github.com/laurahspencer/DuMOAR/issues/43) for the last Salmon run with inputs that we opted to use.

**Comment by ggoetznoaa** [comment]
@laurahspencer Done, where do you want me to put the results, script and log files?

**Comment by laurahspencer** [comment]
Results and log files can go here: https://github.com/laurahspencer/DuMOAR/tree/main/results/salmon
Script can go here: https://github.com/laurahspencer/DuMOAR/tree/main/scripts

Thanks!

**Comment by ggoetznoaa** [comment]
@laurahspencer Ok, the script is located here: https://github.com/laurahspencer/DuMOAR/blob/main/scripts/run.salmon.align.all_original.megan6_trinity_assembly.gcbias.sh

The results is located here: https://github.com/laurahspencer/DuMOAR/tree/main/results/salmon/all_original.megan6_assembly.gcbias

**Comment by laurahspencer** [comment]
@ggoetznoaa can I get access to these alignment files?

**Comment by ggoetznoaa** [comment]
@laurahspencer by default salmon doesn't save mapping information (SAM or BAM files for example). I can re-run salmon with the --writeMappings and possibly --writeUnmappedNames, not sure if the first option will save the information about reads that don't map. Do you want me to re-run salmon? if so which specific salmon runs do you want me to do?

**Comment by laurahspencer** [comment]
I'll get back to you!
