### ISSUE TITLE
Quality trim MBD-BS data

### ISSUE THREAD

**Issue by sr320** [laurahspencer/DuMOAR#8]

**Comment by laurahspencer** [comment]
Trimmed with Trim Galore using the slurm script [trim-mbdbs.sh](https://github.com/laurahspencer/DuMOAR/raw/main/scripts/trim-mbdbs.sh). Followed recommended settings for the Zymo Pico-Methyl kit, as per the [Bismark developers](https://github.com/FelixKrueger/Bismark/tree/master/Docs#ix-notes-about-different-library-types-and-commercial-kits).  The script was written based on the MethCompare project's code.

**Comment by kubu4** [comment]
@laurahspencer - Do you have the FastQC data from _before_ trimming that we could glance at? Might be useful for refence in discussion in Issue #15 .

**Comment by sr320** [comment]
>  Do you have the FastQC data from before trimming that we could glance at?

Straight from seq facility before anything was done to it....

**Comment by laurahspencer** [comment]
Here's the multiQC report on the data that has been concatenated by sample - hhttps://github.com/laurahspencer/DuMOAR/blob/main/data/raw-rnaseq/multiqc_report_raw.html

I'll run fastqc/multiqc on the un-concatenated files now, and will get back to you

**Comment by sr320** [comment]
Thanks - and what type of sequencing was this? paired-end 150bp?

**Comment by laurahspencer** [comment]
As per @kristamnichols and the [fastqc reports](file:///C:/Users/laura.spencer/Downloads/multiqc_report_raw.html), we believe one lane/run was 100bp, and the other was 150bp.

**Comment by sr320** [comment]
Would want to concatenate after trimming. Lets have look at raw fastqc first.

**Comment by laurahspencer** [comment]
> Would want to concatenate after trimming. Lets have look at raw fastqc first.

Why does it matter? - My understanding is that trimming/filtering works on each read separately, so it doesn't make a difference whether trimming occurs before/after concatenating

**Comment by kubu4** [comment]
> Why does it matter?

Had the same thought. Concatenating is just adding lines of text to the end of an existing file, so shouldn't have an impact on anything downstream.

**Comment by sr320** [comment]
Might not.
But two different read lengths? could be two "runs" thus batch effects? I would assess they are similar in MDS. 

And how do we know the trim needs are not different if we have not seen fastqc on raw?

**Comment by sr320** [comment]
What is the first rule of FISH546? :)

**Comment by kubu4** [comment]
> But two different read lengths?

I was assuming the only concatenation taking place were samples from multiple lanes, the same sequencing parameters. 

Certainly would refrain from concatenating a mix of runs with different sequencing params - not sure how downstream software handles FastQs with inconsistent read lengths.

**Comment by laurahspencer** [comment]
Yeah I assumed the same, until I saw the fastqc results, chatted with krista, and realized that i we have a mix of 100bp and 150bp reads. i'll plan to re-run the pipeline with trimming occurring prior to concatenating.

**Comment by kubu4** [comment]
Don't forget to post FastQC/MultiQC of raw, non-concatenated reads. 😃

**Comment by laurahspencer** [comment]
Yup- here you go - 

- [multiqc_report_not-concatenated_4416.html](https://github.com/laurahspencer/DuMOAR/blob/main/data/raw-rnaseq/multiqc_report_not-concatenated_4416.html)
- [multiqc_report_not-concatenated_4417.html](https://github.com/laurahspencer/DuMOAR/blob/main/data/raw-rnaseq/multiqc_report_not-concatenated_4417.html)

**Comment by sr320** [comment]
I am going to suggest only about 20bp are good in one batch and 40bp in the other....

**Comment by sr320** [comment]
>  i'll plan to re-run the pipeline with trimming occurring prior to concatenating.

but run some PCAs / MDS before you concatenate.

**Comment by kubu4** [comment]
> I am going to suggest only about 20bp are good in one batch and 40bp in the other....

I don't think I follow. Can you elaborate on what you mean by this?

**Comment by sr320** [comment]
I am basing that on the fact these lines should essentially be horizontal - https://d.pr/i/mevTec

This is indicative of artificial sequences / adaptors

**Comment by kubu4** [comment]
[Previous quality/trimming results](https://github.com/laurahspencer/DuMOAR/issues/15#issuecomment-1301533710) show ~120bp are good, though.
